#include "ncr.h"
#include <stdint.h>
#include <stdbool.h>

SCSIDevice *hdCreate(void);
void hdReserveStorage(void);
int hdIsDeviceReady(const SCSIDevice *device);
uint32_t hdGetReadSectors(void);
uint32_t hdGetReadIOMicros(void);
const uint8_t *hdGetRawFlashData(void);
bool hdReadSector(unsigned int lba, uint8_t *destination);
uint32_t hdGetWriteSectors(void);
uint32_t hdGetImageSize(void);
int hdIsReady(void);
int hdIsUsingSd(void);
int hdIsReadOnly(void);
uint32_t hdGetCommandCount(void);
uint32_t hdGetUnrecognizedCommandCount(void);
uint32_t hdGetLastCommand(void);
uint32_t hdGetLastLba(void);
uint32_t hdGetLastLength(void);
uint32_t hdGetReadErrorCount(void);
uint32_t hdGetWriteErrorCount(void);
uint32_t hdGetSeekErrorCount(void);
uint32_t hdGetLastIoError(void);
uint32_t hdGetLastReadPrefix(void);
uint32_t hdGetFirstFailureStage(void);
uint32_t hdGetFirstFailureLba(void);
uint32_t hdGetFirstFailureBytes(void);
uint32_t hdGetFirstFailureTransferred(void);
int32_t hdGetFirstFailureSeekResult(void);
int32_t hdGetFirstFailureFlushResult(void);
int32_t hdGetFirstFailureStreamError(void);
int32_t hdGetFirstFailureErrno(void);
uint32_t hdGetOfflineError(void);
uint32_t hdGetOfflineFailureStage(void);
uint32_t hdGetOfflineFailureLba(void);
uint32_t hdGetOfflineFailureBytes(void);
uint32_t hdGetOfflineFailureTransferred(void);
int32_t hdGetOfflineFailureSeekResult(void);
int32_t hdGetOfflineFailureFlushResult(void);
int32_t hdGetOfflineFailureStreamError(void);
int32_t hdGetOfflineFailureErrno(void);
int hdFlushNow(void);
void hdFlushIfDue(void);
void hdInvalidateRawCache(void);
bool hdRawFlashImageIsValid(uint32_t imageBytes);
bool hdRawFlashStorageIsSafe(uint32_t bytes);
uint32_t hdRawFlashStorageAddress(void);
uint32_t hdRawFlashStorageMetadataAddress(void);
uint32_t hdRawFlashStorageMaxImageBytes(void);
bool hdRawFlashStorageRead(uint32_t offset, uint8_t *buffer, size_t bytes);
uint32_t hdGetInstallVolumeBytes(void);
int hdIsInstallVolumeMfs(void);
int hdReadInstallSector(uint32_t sector, uint8_t *destination);
