#include "ncr.h"
#include <stdint.h>
#include <stdbool.h>

SCSIDevice *hdCreate(void);
void hdReserveInstallFile(void);
void hdReserveStorage(void);
bool hdPrepareInstallVolume(void);
int hdIsDeviceReady(const SCSIDevice *device);
const uint8_t *hdGetRawFlashData(void);
bool hdReadSector(unsigned int lba, uint8_t *destination);
uint32_t hdGetImageSize(void);
int hdIsReady(void);
int hdIsUsingSd(void);
int hdIsReadOnly(void);
uint32_t hdGetLastIoError(void);
uint32_t hdGetFirstFailureStage(void);
uint32_t hdGetFirstFailureLba(void);
uint32_t hdGetFirstFailureBytes(void);
uint32_t hdGetFirstFailureTransferred(void);
int32_t hdGetFirstFailureSeekResult(void);
int32_t hdGetFirstFailureFlushResult(void);
int32_t hdGetFirstFailureStreamError(void);
int32_t hdGetFirstFailureErrno(void);
uint32_t hdGetOfflineError(void);
uint32_t hdGetOfflineFailureStage(void);
uint32_t hdGetOfflineFailureLba(void);
uint32_t hdGetOfflineFailureBytes(void);
uint32_t hdGetOfflineFailureTransferred(void);
int32_t hdGetOfflineFailureSeekResult(void);
int32_t hdGetOfflineFailureFlushResult(void);
int32_t hdGetOfflineFailureStreamError(void);
int32_t hdGetOfflineFailureErrno(void);
int hdFlushNow(void);
void hdFlushIfDue(void);
bool hdInvalidateRawCache(void);
bool hdRemoveInstallImage(void);
bool hdRawFlashImageIsValid(uint32_t imageBytes);
bool hdRawFlashStorageIsSafe(uint32_t bytes);
uint32_t hdRawFlashStorageAddress(void);
uint32_t hdRawFlashStorageMetadataAddress(void);
uint32_t hdRawFlashStorageMaxImageBytes(void);
bool hdRawFlashStorageRead(uint32_t offset, uint8_t *buffer, size_t bytes);
uint32_t hdGetInstallVolumeBytes(void);
int hdIsInstallVolumeMfs(void);
int hdIsInstallVolumeReadOnly(void);
int hdReadInstallSector(uint32_t sector, uint8_t *destination);
int hdWriteInstallSector(uint32_t sector, const uint8_t *source);
int hdReadInstallBytes(uint32_t offset, uint8_t *destination, uint32_t bytes);
int hdWriteInstallBytes(uint32_t offset, const uint8_t *source, uint32_t bytes);
int hdFlushInstallVolume(void);
