"""Generate the private standalone partition table before PlatformIO builds.

The table is a build detail, not a user data file. Keeping its small template
here lets a clean checkout build Standard and Full without committing generated
CSV files to the repository.
"""

from pathlib import Path

Import("env")

PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
PIO_ENV = str(env.get("PIOENV", "")).lower()
IS_FULL = PIO_ENV.endswith("-full")
OUTPUT = PROJECT_DIR / ".pio" / "generated" / (
    "partitions-full.csv" if IS_FULL else "partitions-standard.csv"
)

STANDARD = """# Generated by tools/generate_partitions.py.
# Name,   Type, SubType, Offset,   Size
nvs,      data, nvs,     0x9000,   0x5000
factory,  app,  factory, 0x10000,  0x190000
macplus,  data, spiffs,  0x1A0000, 0x4E0000
"""

FULL = """# Generated by tools/generate_partitions.py.
# Name,   Type, SubType, Offset,   Size
nvs,      data, nvs,     0x9000,   0x5000
factory,  app,  factory, 0x10000,  0x190000
macplus,  data, spiffs,  0x1A0000, 0x660000
"""

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text(FULL if IS_FULL else STANDARD, encoding="utf-8")
print("Generated private partition table: {}".format(OUTPUT))
