"""Generate partition tables and packaged firmware images."""

from pathlib import Path

Import("env")

PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
PIO_ENV = str(env.get("PIOENV", "")).lower()
IS_FULL = PIO_ENV.endswith("-full") or PIO_ENV.endswith("-full-debug")
OUTPUT = PROJECT_DIR / ".pio" / "generated" / (
    "partitions-full.csv" if IS_FULL else "partitions-launcher.csv"
)

LAUNCHER = """# Launcher install package layout.
# Name,   Type, SubType, Offset,   Size
nvs,      data, nvs,     0x9000,   0x5000
factory,  app,  factory, 0x10000,  0x190000
macplus,  data, spiffs,  0x1A0000, 0x120000
"""

FULL = """# Generated by tools/generate_partitions.py.
# Name,   Type, SubType, Offset,   Size
nvs,      data, nvs,     0x9000,   0x5000
factory,  app,  factory, 0x10000,  0x190000
macplus,  data, spiffs,  0x1A0000, 0x660000
"""

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text(FULL if IS_FULL else LAUNCHER, encoding="utf-8")
print("Generated private partition table: {}".format(OUTPUT))


def place(image, offset, payload):
    end = offset + len(payload)
    if len(image) < end:
        image.extend(b"\xFF" * (end - len(image)))
    image[offset:end] = payload


def package_firmware(source, target, env):
    build_dir = Path(env.subst("$BUILD_DIR"))
    framework_dir = Path(
        env.PioPlatform().get_package_dir("framework-arduinoespressif32")
    )
    image = bytearray()
    place(image, 0x0000, (build_dir / "bootloader.bin").read_bytes())
    place(image, 0x8000, (build_dir / "partitions.bin").read_bytes())
    place(
        image,
        0xE000,
        (framework_dir / "tools" / "partitions" / "boot_app0.bin").read_bytes(),
    )
    place(image, 0x10000, (build_dir / "firmware.bin").read_bytes())

    # Launcher treats an empty data entry as its default 448 KiB SPIFFS. A
    # tiny non-empty payload makes it honor the declared macplus size; the
    # emulator replaces this invalid metadata marker when it imports hd.img.
    if not IS_FULL:
        place(image, 0x1A0000, b"MACPLUS-DATA-V1\n")

    package_kind = "full" if IS_FULL else "launcher"
    debug_suffix = "-debug" if "debug" in PIO_ENV else ""
    output_name = "macplus-{}{}.bin".format(package_kind, debug_suffix)
    output_path = PROJECT_DIR / output_name
    output_path.write_bytes(image)
    print("Packaged firmware: {} ({} bytes)".format(output_path, len(image)))


env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", package_firmware)
